package tela;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author walmi
 */
public class JogoGekitai extends javax.swing.JFrame {

    
    public JogoGekitai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPanel = new javax.swing.JPanel();
        tabuleiroPanelImagem = new componentes.UJPanelImagem();
        a1Label = new javax.swing.JLabel();
        a2Label = new javax.swing.JLabel();
        a3Label = new javax.swing.JLabel();
        a4Label = new javax.swing.JLabel();
        a5Label = new javax.swing.JLabel();
        a6Label = new javax.swing.JLabel();
        b1Label = new javax.swing.JLabel();
        b2Label = new javax.swing.JLabel();
        b3Label = new javax.swing.JLabel();
        b4Label = new javax.swing.JLabel();
        b5Label = new javax.swing.JLabel();
        b6Label = new javax.swing.JLabel();
        c1Label = new javax.swing.JLabel();
        c2Label = new javax.swing.JLabel();
        c3Label = new javax.swing.JLabel();
        c4Label = new javax.swing.JLabel();
        c5Label = new javax.swing.JLabel();
        c6Label = new javax.swing.JLabel();
        d1Label = new javax.swing.JLabel();
        d2Label = new javax.swing.JLabel();
        d3Label = new javax.swing.JLabel();
        d4Label = new javax.swing.JLabel();
        d5Label = new javax.swing.JLabel();
        d6Label = new javax.swing.JLabel();
        e1Label = new javax.swing.JLabel();
        e2Label = new javax.swing.JLabel();
        e3Label = new javax.swing.JLabel();
        e4Label = new javax.swing.JLabel();
        e5Label = new javax.swing.JLabel();
        e6Label = new javax.swing.JLabel();
        f1Label = new javax.swing.JLabel();
        f2Label = new javax.swing.JLabel();
        f3Label = new javax.swing.JLabel();
        f4Label = new javax.swing.JLabel();
        f5Label = new javax.swing.JLabel();
        f6Label = new javax.swing.JLabel();
        chatPanel = new javax.swing.JPanel();
        tituloChatLabel = new javax.swing.JLabel();
        conversaScrollPane = new javax.swing.JScrollPane();
        conversaTextArea = new javax.swing.JTextArea();
        mensagemTextField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();
        statusJogoLabel = new javax.swing.JLabel();
        caixaPecasPanel = new javax.swing.JPanel();
        p1Label = new javax.swing.JLabel();
        p2Label = new javax.swing.JLabel();
        p3Label = new javax.swing.JLabel();
        p4Label = new javax.swing.JLabel();
        p5Label = new javax.swing.JLabel();
        p6Label = new javax.swing.JLabel();
        p7Label = new javax.swing.JLabel();
        p8Label = new javax.swing.JLabel();
        selecaPecaLabel = new javax.swing.JLabel();
        barraMenusPanel = new javax.swing.JPanel();
        iniciarJogoButton = new javax.swing.JButton();
        desistirJogoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        telaPanel.setBackground(new java.awt.Color(245, 245, 245));

        tabuleiroPanelImagem.setImagem(new java.io.File("C:\\Users\\walmi\\Documents\\NetBeansProjects\\Gekitai\\src\\tela\\tabuleiro.png"));

        a1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a1LabelMouseExited(evt);
            }
        });

        a2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a2LabelMouseExited(evt);
            }
        });

        a3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a3LabelMouseExited(evt);
            }
        });

        a4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a4LabelMouseExited(evt);
            }
        });

        a5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a5LabelMouseExited(evt);
            }
        });

        a6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a6LabelMouseExited(evt);
            }
        });

        b1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1LabelMouseExited(evt);
            }
        });

        b2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2LabelMouseExited(evt);
            }
        });

        b3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3LabelMouseExited(evt);
            }
        });

        b4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4LabelMouseExited(evt);
            }
        });

        b5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b5LabelMouseExited(evt);
            }
        });

        b6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b6LabelMouseExited(evt);
            }
        });

        c1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c1LabelMouseExited(evt);
            }
        });

        c2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c2LabelMouseExited(evt);
            }
        });

        c3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c3LabelMouseExited(evt);
            }
        });

        c4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c4LabelMouseExited(evt);
            }
        });

        c5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c5LabelMouseExited(evt);
            }
        });

        c6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c6LabelMouseExited(evt);
            }
        });

        d1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d1LabelMouseExited(evt);
            }
        });

        d2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d2LabelMouseExited(evt);
            }
        });

        d3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d3LabelMouseExited(evt);
            }
        });

        d4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d4LabelMouseExited(evt);
            }
        });

        d5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d5LabelMouseExited(evt);
            }
        });

        d6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d6Label.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                d6LabelFocusGained(evt);
            }
        });
        d6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                d6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                d6LabelMouseExited(evt);
            }
        });

        e1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e1LabelMouseExited(evt);
            }
        });

        e2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e2LabelMouseExited(evt);
            }
        });

        e3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e3LabelMouseExited(evt);
            }
        });

        e4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e4LabelMouseExited(evt);
            }
        });

        e5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e5LabelMouseExited(evt);
            }
        });

        e6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e6LabelMouseExited(evt);
            }
        });

        f1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f1LabelMouseExited(evt);
            }
        });

        f2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f2LabelMouseExited(evt);
            }
        });

        f3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f3LabelMouseExited(evt);
            }
        });

        f4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f4LabelMouseExited(evt);
            }
        });

        f5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f5LabelMouseExited(evt);
            }
        });

        f6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f6LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tabuleiroPanelImagemLayout = new javax.swing.GroupLayout(tabuleiroPanelImagem);
        tabuleiroPanelImagem.setLayout(tabuleiroPanelImagemLayout);
        tabuleiroPanelImagemLayout.setHorizontalGroup(
            tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(a1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addComponent(b3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addComponent(b6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addComponent(d1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(e1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addComponent(d2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(e2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addComponent(d4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(e4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addComponent(d3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(e3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addComponent(d5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(e5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addComponent(d6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tabuleiroPanelImagemLayout.setVerticalGroup(
            tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addComponent(a1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d1Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e1Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f1Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b2Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d2Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e2Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f2Label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabuleiroPanelImagemLayout.createSequentialGroup()
                                .addComponent(f3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(c3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabuleiroPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        chatPanel.setBackground(new java.awt.Color(255, 255, 255));

        tituloChatLabel.setText("Jogue Gekitai!");

        conversaTextArea.setEditable(false);
        conversaTextArea.setBackground(new java.awt.Color(255, 255, 255));
        conversaTextArea.setColumns(20);
        conversaTextArea.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        conversaTextArea.setLineWrap(true);
        conversaTextArea.setRows(5);
        conversaTextArea.setBorder(null);
        conversaScrollPane.setViewportView(conversaTextArea);

        mensagemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensagemTextFieldActionPerformed(evt);
            }
        });

        enviarButton.setText("✈");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        statusJogoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusJogoLabel.setText("Clique no botão iniciar para começar a jogar");

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chatPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(tituloChatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chatPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatPanelLayout.createSequentialGroup()
                                .addComponent(mensagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(statusJogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(conversaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13))
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tituloChatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conversaScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusJogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        caixaPecasPanel.setBackground(new java.awt.Color(245, 245, 245));

        p1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p1LabelMouseExited(evt);
            }
        });

        p2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p2LabelMouseExited(evt);
            }
        });

        p3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p3LabelMouseExited(evt);
            }
        });

        p4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p4LabelMouseExited(evt);
            }
        });

        p5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p5LabelMouseExited(evt);
            }
        });

        p6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p6LabelMouseExited(evt);
            }
        });

        p7Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p7LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p7LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p7LabelMouseExited(evt);
            }
        });

        p8Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p8LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p8LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p8LabelMouseExited(evt);
            }
        });

        selecaPecaLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        selecaPecaLabel.setForeground(new java.awt.Color(0, 102, 0));
        selecaPecaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout caixaPecasPanelLayout = new javax.swing.GroupLayout(caixaPecasPanel);
        caixaPecasPanel.setLayout(caixaPecasPanelLayout);
        caixaPecasPanelLayout.setHorizontalGroup(
            caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                        .addComponent(p2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(p1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(p3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(p6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selecaPecaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        caixaPecasPanelLayout.setVerticalGroup(
            caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caixaPecasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caixaPecasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selecaPecaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        barraMenusPanel.setBackground(new java.awt.Color(245, 245, 245));

        iniciarJogoButton.setBackground(new java.awt.Color(153, 255, 153));
        iniciarJogoButton.setText("INICIAR ▶");
        iniciarJogoButton.setBorderPainted(false);
        iniciarJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJogoButtonActionPerformed(evt);
            }
        });

        desistirJogoButton.setBackground(new java.awt.Color(204, 204, 204));
        desistirJogoButton.setText("DESISTIR ⏹");
        desistirJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desistirJogoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraMenusPanelLayout = new javax.swing.GroupLayout(barraMenusPanel);
        barraMenusPanel.setLayout(barraMenusPanelLayout);
        barraMenusPanelLayout.setHorizontalGroup(
            barraMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraMenusPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(iniciarJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(desistirJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barraMenusPanelLayout.setVerticalGroup(
            barraMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraMenusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraMenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iniciarJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desistirJogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telaPanelLayout = new javax.swing.GroupLayout(telaPanel);
        telaPanel.setLayout(telaPanelLayout);
        telaPanelLayout.setHorizontalGroup(
            telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabuleiroPanelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caixaPecasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraMenusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(chatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        telaPanelLayout.setVerticalGroup(
            telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPanelLayout.createSequentialGroup()
                .addGroup(telaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(telaPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(barraMenusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabuleiroPanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caixaPecasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a1LabelMouseClicked

    private void a1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a1LabelMouseEntered

    private void a1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a1LabelMouseExited

    private void a2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a2LabelMouseClicked

    private void a2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a2LabelMouseEntered

    private void a2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a2LabelMouseExited

    private void a3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a3LabelMouseClicked

    private void a3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a3LabelMouseEntered

    private void a3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a3LabelMouseExited

    private void b3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b3LabelMouseClicked

    private void b3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b3LabelMouseEntered

    private void b3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b3LabelMouseExited

    private void b2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b2LabelMouseClicked

    private void b2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b2LabelMouseEntered

    private void b2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b2LabelMouseExited

    private void b1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b1LabelMouseClicked

    private void b1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b1LabelMouseEntered

    private void b1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b1LabelMouseExited

    private void d2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d2LabelMouseClicked

    private void d2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d2LabelMouseEntered

    private void d2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d2LabelMouseExited

    private void c1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c1LabelMouseClicked

    private void c1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c1LabelMouseEntered

    private void c1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c1LabelMouseExited

    private void d4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d4LabelMouseClicked

    private void d4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d4LabelMouseEntered

    private void d4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d4LabelMouseExited

    private void f1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f1LabelMouseClicked

    private void f1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f1LabelMouseEntered

    private void f1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f1LabelMouseExited

    private void c2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c2LabelMouseClicked

    private void c2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c2LabelMouseEntered

    private void c2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c2LabelMouseExited

    private void c4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c4LabelMouseClicked

    private void c4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c4LabelMouseEntered

    private void c4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c4LabelMouseExited

    private void e2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e2LabelMouseClicked

    private void e2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e2LabelMouseEntered

    private void e2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e2LabelMouseExited

    private void f4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f4LabelMouseClicked

    private void f4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f4LabelMouseEntered

    private void f4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f4LabelMouseExited

    private void e3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e3LabelMouseClicked

    private void e3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e3LabelMouseEntered

    private void e3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e3LabelMouseExited

    private void d5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d5LabelMouseClicked

    private void d5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d5LabelMouseEntered

    private void d5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d5LabelMouseExited

    private void d6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d6LabelMouseClicked

    private void d6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d6LabelMouseEntered

    private void d6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d6LabelMouseExited

    private void d6LabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d6LabelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_d6LabelFocusGained

    private void e1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e1LabelMouseClicked

    private void e1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e1LabelMouseEntered

    private void e1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e1LabelMouseExited

    private void a4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a4LabelMouseClicked

    private void a4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a4LabelMouseEntered

    private void a4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a4LabelMouseExited

    private void f2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f2LabelMouseClicked

    private void f2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f2LabelMouseEntered

    private void f2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f2LabelMouseExited

    private void f3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f3LabelMouseClicked

    private void f3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f3LabelMouseEntered

    private void f3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f3LabelMouseExited

    private void a5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a5LabelMouseClicked

    private void a5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a5LabelMouseEntered

    private void a5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a5LabelMouseExited

    private void d1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d1LabelMouseClicked

    private void d1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d1LabelMouseEntered

    private void d1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d1LabelMouseExited

    private void a6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_a6LabelMouseClicked

    private void a6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_a6LabelMouseEntered

    private void a6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_a6LabelMouseExited

    private void b4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b4LabelMouseClicked

    private void b4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b4LabelMouseEntered

    private void b4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b4LabelMouseExited

    private void b5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b5LabelMouseClicked

    private void b5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b5LabelMouseEntered

    private void b5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b5LabelMouseExited

    private void b6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b6LabelMouseClicked

    private void b6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b6LabelMouseEntered

    private void b6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b6LabelMouseExited

    private void c5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c5LabelMouseClicked

    private void c5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c5LabelMouseEntered

    private void c5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c5LabelMouseExited

    private void c6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c6LabelMouseClicked

    private void c6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c6LabelMouseEntered

    private void c6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c6LabelMouseExited

    private void e4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e4LabelMouseClicked

    private void e4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e4LabelMouseEntered

    private void e4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e4LabelMouseExited

    private void e5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e5LabelMouseClicked

    private void e5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e5LabelMouseEntered

    private void e5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e5LabelMouseExited

    private void e6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_e6LabelMouseClicked

    private void e6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e6LabelMouseEntered

    private void e6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e6LabelMouseExited

    private void f5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f5LabelMouseClicked

    private void f5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f5LabelMouseEntered

    private void f5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f5LabelMouseExited

    private void f6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_f6LabelMouseClicked

    private void f6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_f6LabelMouseEntered

    private void f6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_f6LabelMouseExited

    private void c3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c3LabelMouseClicked

    private void c3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_c3LabelMouseEntered

    private void c3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_c3LabelMouseExited

    private void d3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_d3LabelMouseClicked

    private void d3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_d3LabelMouseEntered

    private void d3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_d3LabelMouseExited

    private void mensagemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensagemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensagemTextFieldActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void p1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p1LabelMouseClicked

    private void p1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p1LabelMouseEntered

    private void p1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p1LabelMouseExited

    private void p2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p2LabelMouseClicked

    private void p2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p2LabelMouseEntered

    private void p2LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p2LabelMouseExited

    private void p3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p3LabelMouseClicked

    private void p3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p3LabelMouseEntered

    private void p3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p3LabelMouseExited

    private void p4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p4LabelMouseClicked

    private void p4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p4LabelMouseEntered

    private void p4LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p4LabelMouseExited

    private void p5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p5LabelMouseClicked

    private void p5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p5LabelMouseEntered

    private void p5LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p5LabelMouseExited

    private void p6LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p6LabelMouseClicked

    private void p6LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p6LabelMouseEntered

    private void p6LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p6LabelMouseExited

    private void p7LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p7LabelMouseClicked

    private void p7LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p7LabelMouseEntered

    private void p7LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p7LabelMouseExited

    private void p8LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8LabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p8LabelMouseClicked

    private void p8LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p8LabelMouseEntered

    private void p8LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p8LabelMouseExited

    private void iniciarJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarJogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarJogoButtonActionPerformed

    private void desistirJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desistirJogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desistirJogoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoGekitai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoGekitai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoGekitai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoGekitai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoGekitai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1Label;
    private javax.swing.JLabel a2Label;
    private javax.swing.JLabel a3Label;
    private javax.swing.JLabel a4Label;
    private javax.swing.JLabel a5Label;
    private javax.swing.JLabel a6Label;
    private javax.swing.JLabel b1Label;
    private javax.swing.JLabel b2Label;
    private javax.swing.JLabel b3Label;
    private javax.swing.JLabel b4Label;
    private javax.swing.JLabel b5Label;
    private javax.swing.JLabel b6Label;
    private javax.swing.JPanel barraMenusPanel;
    private javax.swing.JLabel c1Label;
    private javax.swing.JLabel c2Label;
    private javax.swing.JLabel c3Label;
    private javax.swing.JLabel c4Label;
    private javax.swing.JLabel c5Label;
    private javax.swing.JLabel c6Label;
    private javax.swing.JPanel caixaPecasPanel;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JScrollPane conversaScrollPane;
    public javax.swing.JTextArea conversaTextArea;
    private javax.swing.JLabel d1Label;
    private javax.swing.JLabel d2Label;
    private javax.swing.JLabel d3Label;
    private javax.swing.JLabel d4Label;
    private javax.swing.JLabel d5Label;
    private javax.swing.JLabel d6Label;
    private javax.swing.JButton desistirJogoButton;
    private javax.swing.JLabel e1Label;
    private javax.swing.JLabel e2Label;
    private javax.swing.JLabel e3Label;
    private javax.swing.JLabel e4Label;
    private javax.swing.JLabel e5Label;
    private javax.swing.JLabel e6Label;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel f1Label;
    private javax.swing.JLabel f2Label;
    private javax.swing.JLabel f3Label;
    private javax.swing.JLabel f4Label;
    private javax.swing.JLabel f5Label;
    private javax.swing.JLabel f6Label;
    private javax.swing.JButton iniciarJogoButton;
    private javax.swing.JTextField mensagemTextField;
    private javax.swing.JLabel p1Label;
    private javax.swing.JLabel p2Label;
    private javax.swing.JLabel p3Label;
    private javax.swing.JLabel p4Label;
    private javax.swing.JLabel p5Label;
    private javax.swing.JLabel p6Label;
    private javax.swing.JLabel p7Label;
    private javax.swing.JLabel p8Label;
    private javax.swing.JLabel selecaPecaLabel;
    private javax.swing.JLabel statusJogoLabel;
    private componentes.UJPanelImagem tabuleiroPanelImagem;
    private javax.swing.JPanel telaPanel;
    private javax.swing.JLabel tituloChatLabel;
    // End of variables declaration//GEN-END:variables

    public JLabel getA1Label() {
        return a1Label;
    }

    public JLabel getA2Label() {
        return a2Label;
    }

    public JLabel getA3Label() {
        return a3Label;
    }

    public JLabel getA4Label() {
        return a4Label;
    }

    public JLabel getA5Label() {
        return a5Label;
    }

    public JLabel getA6Label() {
        return a6Label;
    }

    public JLabel getB1Label() {
        return b1Label;
    }

    public JLabel getB2Label() {
        return b2Label;
    }

    public JLabel getB3Label() {
        return b3Label;
    }

    public JLabel getB4Label() {
        return b4Label;
    }

    public JLabel getB5Label() {
        return b5Label;
    }

    public JLabel getB6Label() {
        return b6Label;
    }

    public JPanel getBarraMenusPanel() {
        return barraMenusPanel;
    }

    public JLabel getC1Label() {
        return c1Label;
    }

    public JLabel getC2Label() {
        return c2Label;
    }

    public JLabel getC3Label() {
        return c3Label;
    }

    public JLabel getC4Label() {
        return c4Label;
    }

    public JLabel getC5Label() {
        return c5Label;
    }

    public JLabel getC6Label() {
        return c6Label;
    }

    public JLabel getD1Label() {
        return d1Label;
    }

    public JLabel getD2Label() {
        return d2Label;
    }

    public JLabel getD3Label() {
        return d3Label;
    }

    public JLabel getD4Label() {
        return d4Label;
    }

    public JLabel getD5Label() {
        return d5Label;
    }

    public JLabel getD6Label() {
        return d6Label;
    }

    public JLabel getE1Label() {
        return e1Label;
    }

    public JLabel getE2Label() {
        return e2Label;
    }

    public JLabel getE3Label() {
        return e3Label;
    }

    public JLabel getE4Label() {
        return e4Label;
    }

    public JLabel getE5Label() {
        return e5Label;
    }

    public JLabel getE6Label() {
        return e6Label;
    }

    public JLabel getF1Label() {
        return f1Label;
    }

    public JLabel getF2Label() {
        return f2Label;
    }

    public JLabel getF3Label() {
        return f3Label;
    }

    public JLabel getF4Label() {
        return f4Label;
    }

    public JLabel getF5Label() {
        return f5Label;
    }

    public JLabel getF6Label() {
        return f6Label;
    }

    public JLabel getP1Label() {
        return p1Label;
    }

    public JLabel getP2Label() {
        return p2Label;
    }

    public JLabel getP3Label() {
        return p3Label;
    }

    public JLabel getP4Label() {
        return p4Label;
    }

    public JLabel getP5Label() {
        return p5Label;
    }

    public JLabel getP6Label() {
        return p6Label;
    }

    public JLabel getP7Label() {
        return p7Label;
    }

    public JLabel getP8Label() {
        return p8Label;
    }

    public JButton getDesistirJogoButton() {
        return desistirJogoButton;
    }

    public JButton getEnviarButton() {
        return enviarButton;
    }

    public JButton getIniciarJogoButton() {
        return iniciarJogoButton;
    }
    
    public JLabel getStatusJogoLabel(){ return statusJogoLabel; }
    public JLabel getSelecaoPecaLabel() { return selecaPecaLabel; }
    public JTextArea getConversaTextArea(){ return conversaTextArea; }
    public JTextField getMensagemTextField() { return mensagemTextField; }
}
